//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.PrintViewDesigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.PrintViewDesigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string AppearanceCategory {
            get {
                return ResourceManager.GetString("AppearanceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string BackgroundProperty {
            get {
                return ResourceManager.GetString("BackgroundProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string BarcodeCategory {
            get {
                return ResourceManager.GetString("BarcodeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalcCheckSum.
        /// </summary>
        public static string BarcodeEan13CalcCheckSumProperty {
            get {
                return ResourceManager.GetString("BarcodeEan13CalcCheckSumProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string BarcodeEan13RotationProperty {
            get {
                return ResourceManager.GetString("BarcodeEan13RotationProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WideBarRatio.
        /// </summary>
        public static string BarcodeEan13WideBarRatioProperty {
            get {
                return ResourceManager.GetString("BarcodeEan13WideBarRatioProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCorrection.
        /// </summary>
        public static string BarcodeQrErrorCorrectionProperty {
            get {
                return ResourceManager.GetString("BarcodeQrErrorCorrectionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string BarcodeQrRotationProperty {
            get {
                return ResourceManager.GetString("BarcodeQrRotationProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean, &apos;{0}&apos;, &apos;{1}&apos;.
        /// </summary>
        public static string BooleanFormat {
            get {
                return ResourceManager.GetString("BooleanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False value text:.
        /// </summary>
        public static string BooleanFormatFalseText {
            get {
                return ResourceManager.GetString("BooleanFormatFalseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        public static string BooleanFormatTabHeader {
            get {
                return ResourceManager.GetString("BooleanFormatTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True value text:.
        /// </summary>
        public static string BooleanFormatTrueText {
            get {
                return ResourceManager.GetString("BooleanFormatTrueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string BorderColorProperty {
            get {
                return ResourceManager.GetString("BorderColorProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        public static string BorderProperty {
            get {
                return ResourceManager.GetString("BorderProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        public static string BorderThicknessProperty {
            get {
                return ResourceManager.GetString("BorderThicknessProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element cannot be pasted into itself..
        /// </summary>
        public static string CannotBePastedIntoItself {
            get {
                return ResourceManager.GetString("CannotBePastedIntoItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not allowed to insert &apos;{0}&apos; into &apos;{1}&apos;..
        /// </summary>
        public static string CannotInsertChildElement {
            get {
                return ResourceManager.GetString("CannotInsertChildElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination element &apos;{0}&apos; is a subitem of the source element &apos;{1}&apos;..
        /// </summary>
        public static string CannotInsertParentIntoChild {
            get {
                return ResourceManager.GetString("CannotInsertParentIntoChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        public static string CaptionProperty {
            get {
                return ResourceManager.GetString("CaptionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string ColumnSizeProperty {
            get {
                return ResourceManager.GetString("ColumnSizeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SizeUnit.
        /// </summary>
        public static string ColumnSizeUnitProperty {
            get {
                return ResourceManager.GetString("ColumnSizeUnitProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string CommonCategory {
            get {
                return ResourceManager.GetString("CommonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DataCategory {
            get {
                return ResourceManager.GetString("DataCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime, &apos;{0}&apos;.
        /// </summary>
        public static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string DateTimeFormatSample {
            get {
                return ResourceManager.GetString("DateTimeFormatSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        public static string DateTimeFormatTabHeader {
            get {
                return ResourceManager.GetString("DateTimeFormatTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete element &apos;{0}&apos;?.
        /// </summary>
        public static string DeleteElementQuestion {
            get {
                return ResourceManager.GetString("DeleteElementQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionProperty {
            get {
                return ResourceManager.GetString("DescriptionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        public static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to File.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string FontFamilyProperty {
            get {
                return ResourceManager.GetString("FontFamilyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string FontProperty {
            get {
                return ResourceManager.GetString("FontProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string FontSizeProperty {
            get {
                return ResourceManager.GetString("FontSizeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SizeUnit.
        /// </summary>
        public static string FontSizeUnitProperty {
            get {
                return ResourceManager.GetString("FontSizeUnitProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condensed.
        /// </summary>
        public static string FontStretchCondensed {
            get {
                return ResourceManager.GetString("FontStretchCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded.
        /// </summary>
        public static string FontStretchExpanded {
            get {
                return ResourceManager.GetString("FontStretchExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraCondensed.
        /// </summary>
        public static string FontStretchExtraCondensed {
            get {
                return ResourceManager.GetString("FontStretchExtraCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraExpanded.
        /// </summary>
        public static string FontStretchExtraExpanded {
            get {
                return ResourceManager.GetString("FontStretchExtraExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string FontStretchNormal {
            get {
                return ResourceManager.GetString("FontStretchNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        public static string FontStretchProperty {
            get {
                return ResourceManager.GetString("FontStretchProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SemiCondensed.
        /// </summary>
        public static string FontStretchSemiCondensed {
            get {
                return ResourceManager.GetString("FontStretchSemiCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SemiExpanded.
        /// </summary>
        public static string FontStretchSemiExpanded {
            get {
                return ResourceManager.GetString("FontStretchSemiExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UltraCondensed.
        /// </summary>
        public static string FontStretchUltraCondensed {
            get {
                return ResourceManager.GetString("FontStretchUltraCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UltraExpanded.
        /// </summary>
        public static string FontStretchUltraExpanded {
            get {
                return ResourceManager.GetString("FontStretchUltraExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string FontStyleItalic {
            get {
                return ResourceManager.GetString("FontStyleItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string FontStyleNormal {
            get {
                return ResourceManager.GetString("FontStyleNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblique.
        /// </summary>
        public static string FontStyleOblique {
            get {
                return ResourceManager.GetString("FontStyleOblique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string FontStyleProperty {
            get {
                return ResourceManager.GetString("FontStyleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string FontVariantNormal {
            get {
                return ResourceManager.GetString("FontVariantNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant.
        /// </summary>
        public static string FontVariantProperty {
            get {
                return ResourceManager.GetString("FontVariantProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        public static string FontVariantSubscript {
            get {
                return ResourceManager.GetString("FontVariantSubscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        public static string FontVariantSuperscript {
            get {
                return ResourceManager.GetString("FontVariantSuperscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string FontWeightBold {
            get {
                return ResourceManager.GetString("FontWeightBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraBold.
        /// </summary>
        public static string FontWeightExtraBold {
            get {
                return ResourceManager.GetString("FontWeightExtraBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraLight.
        /// </summary>
        public static string FontWeightExtraLight {
            get {
                return ResourceManager.GetString("FontWeightExtraLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string FontWeightLight {
            get {
                return ResourceManager.GetString("FontWeightLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string FontWeightMedium {
            get {
                return ResourceManager.GetString("FontWeightMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string FontWeightNormal {
            get {
                return ResourceManager.GetString("FontWeightNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string FontWeightProperty {
            get {
                return ResourceManager.GetString("FontWeightProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SemiBold.
        /// </summary>
        public static string FontWeightSemiBold {
            get {
                return ResourceManager.GetString("FontWeightSemiBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UltraBold.
        /// </summary>
        public static string FontWeightUltraBold {
            get {
                return ResourceManager.GetString("FontWeightUltraBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UltraLight.
        /// </summary>
        public static string FontWeightUltraLight {
            get {
                return ResourceManager.GetString("FontWeightUltraLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        public static string ForegroundProperty {
            get {
                return ResourceManager.GetString("ForegroundProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralFormatTabHeader {
            get {
                return ResourceManager.GetString("GeneralFormatTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string HyperlinkReferenceProperty {
            get {
                return ResourceManager.GetString("HyperlinkReferenceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceFormat.
        /// </summary>
        public static string HyperlinkSourceFormatProperty {
            get {
                return ResourceManager.GetString("HyperlinkSourceFormatProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageCategory {
            get {
                return ResourceManager.GetString("ImageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string ImageDataProperty {
            get {
                return ResourceManager.GetString("ImageDataProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string ImageRotationProperty {
            get {
                return ResourceManager.GetString("ImageRotationProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string ImageSizeProperty {
            get {
                return ResourceManager.GetString("ImageSizeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string ImageStretchFill {
            get {
                return ResourceManager.GetString("ImageStretchFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ImageStretchNone {
            get {
                return ResourceManager.GetString("ImageStretchNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        public static string ImageStretchProperty {
            get {
                return ResourceManager.GetString("ImageStretchProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform.
        /// </summary>
        public static string ImageStretchUniform {
            get {
                return ResourceManager.GetString("ImageStretchUniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from File.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect element.
        /// </summary>
        public static string InspectElement {
            get {
                return ResourceManager.GetString("InspectElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string LayoutCategory {
            get {
                return ResourceManager.GetString("LayoutCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string ListCategory {
            get {
                return ResourceManager.GetString("ListCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string ListItems {
            get {
                return ResourceManager.GetString("ListItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemTemplate.
        /// </summary>
        public static string ListItemTemplate {
            get {
                return ResourceManager.GetString("ListItemTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarkerOffset.
        /// </summary>
        public static string ListMarkerOffset {
            get {
                return ResourceManager.GetString("ListMarkerOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarkerOffsetSize.
        /// </summary>
        public static string ListMarkerOffsetSizeProperty {
            get {
                return ResourceManager.GetString("ListMarkerOffsetSizeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarkerOffsetSizeUnit.
        /// </summary>
        public static string ListMarkerOffsetSizeUnitProperty {
            get {
                return ResourceManager.GetString("ListMarkerOffsetSizeUnitProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        public static string ListMarkerStyleBox {
            get {
                return ResourceManager.GetString("ListMarkerStyleBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string ListMarkerStyleCircle {
            get {
                return ResourceManager.GetString("ListMarkerStyleCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        public static string ListMarkerStyleDecimal {
            get {
                return ResourceManager.GetString("ListMarkerStyleDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc.
        /// </summary>
        public static string ListMarkerStyleDisc {
            get {
                return ResourceManager.GetString("ListMarkerStyleDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LowerLatin.
        /// </summary>
        public static string ListMarkerStyleLowerLatin {
            get {
                return ResourceManager.GetString("ListMarkerStyleLowerLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LowerRoman.
        /// </summary>
        public static string ListMarkerStyleLowerRoman {
            get {
                return ResourceManager.GetString("ListMarkerStyleLowerRoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ListMarkerStyleNone {
            get {
                return ResourceManager.GetString("ListMarkerStyleNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarkerStyle.
        /// </summary>
        public static string ListMarkerStyleProperty {
            get {
                return ResourceManager.GetString("ListMarkerStyleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string ListMarkerStyleSquare {
            get {
                return ResourceManager.GetString("ListMarkerStyleSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpperLatin.
        /// </summary>
        public static string ListMarkerStyleUpperLatin {
            get {
                return ResourceManager.GetString("ListMarkerStyleUpperLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpperRoman.
        /// </summary>
        public static string ListMarkerStyleUpperRoman {
            get {
                return ResourceManager.GetString("ListMarkerStyleUpperRoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartIndex.
        /// </summary>
        public static string ListStartIndexProperty {
            get {
                return ResourceManager.GetString("ListStartIndexProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        public static string MarginProperty {
            get {
                return ResourceManager.GetString("MarginProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameProperty {
            get {
                return ResourceManager.GetString("NameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number, &apos;{0}&apos;.
        /// </summary>
        public static string NumberFormat {
            get {
                return ResourceManager.GetString("NumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string NumberFormatSample {
            get {
                return ResourceManager.GetString("NumberFormatSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string NumberFormatTabHeader {
            get {
                return ResourceManager.GetString("NumberFormatTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object, &apos;{0}&apos;.
        /// </summary>
        public static string ObjectFormat {
            get {
                return ResourceManager.GetString("ObjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string ObjectFormatTabHeader {
            get {
                return ResourceManager.GetString("ObjectFormatTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        public static string PaddingProperty {
            get {
                return ResourceManager.GetString("PaddingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string PageCategory {
            get {
                return ResourceManager.GetString("PageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        public static string PagePaddingProperty {
            get {
                return ResourceManager.GetString("PagePaddingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string PageSizeProperty {
            get {
                return ResourceManager.GetString("PageSizeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent.
        /// </summary>
        public static string ParagraphIndent {
            get {
                return ResourceManager.GetString("ParagraphIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndentSize.
        /// </summary>
        public static string ParagraphIndentSizeProperty {
            get {
                return ResourceManager.GetString("ParagraphIndentSizeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndentSizeUnit.
        /// </summary>
        public static string ParagraphIndentSizeUnitProperty {
            get {
                return ResourceManager.GetString("ParagraphIndentSizeUnitProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Data.
        /// </summary>
        public static string PreviewData {
            get {
                return ResourceManager.GetString("PreviewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview as HTML.
        /// </summary>
        public static string PreviewHtml {
            get {
                return ResourceManager.GetString("PreviewHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview as PDF.
        /// </summary>
        public static string PreviewPdf {
            get {
                return ResourceManager.GetString("PreviewPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN13.
        /// </summary>
        public static string PrintBarcodeEan13Node {
            get {
                return ResourceManager.GetString("PrintBarcodeEan13Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR.
        /// </summary>
        public static string PrintBarcodeQrNode {
            get {
                return ResourceManager.GetString("PrintBarcodeQrNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string PrintBoldNode {
            get {
                return ResourceManager.GetString("PrintBoldNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks.
        /// </summary>
        public static string PrintDocumentBlocksNode {
            get {
                return ResourceManager.GetString("PrintDocumentBlocksNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string PrintDocumentNode {
            get {
                return ResourceManager.GetString("PrintDocumentNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string PrintDocumentStylesNode {
            get {
                return ResourceManager.GetString("PrintDocumentStylesNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PrintElementPropertyDockPanel {
            get {
                return ResourceManager.GetString("PrintElementPropertyDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink.
        /// </summary>
        public static string PrintHyperlinkNode {
            get {
                return ResourceManager.GetString("PrintHyperlinkNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string PrintImageNode {
            get {
                return ResourceManager.GetString("PrintImageNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string PrintItalicNode {
            get {
                return ResourceManager.GetString("PrintItalicNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineBreak.
        /// </summary>
        public static string PrintLineBreakNode {
            get {
                return ResourceManager.GetString("PrintLineBreakNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string PrintLineNode {
            get {
                return ResourceManager.GetString("PrintLineNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string PrintListItemsNode {
            get {
                return ResourceManager.GetString("PrintListItemsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemTemplate.
        /// </summary>
        public static string PrintListItemTemplateNode {
            get {
                return ResourceManager.GetString("PrintListItemTemplateNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string PrintListNode {
            get {
                return ResourceManager.GetString("PrintListNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageBreak.
        /// </summary>
        public static string PrintPageBreakNode {
            get {
                return ResourceManager.GetString("PrintPageBreakNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        public static string PrintParagraphNode {
            get {
                return ResourceManager.GetString("PrintParagraphNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string PrintRunNode {
            get {
                return ResourceManager.GetString("PrintRunNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        public static string PrintSectionNode {
            get {
                return ResourceManager.GetString("PrintSectionNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span.
        /// </summary>
        public static string PrintSpanNode {
            get {
                return ResourceManager.GetString("PrintSpanNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string PrintStyleNode {
            get {
                return ResourceManager.GetString("PrintStyleNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string PrintTableCellNode {
            get {
                return ResourceManager.GetString("PrintTableCellNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellTemplate.
        /// </summary>
        public static string PrintTableColumnCellTemplateNode {
            get {
                return ResourceManager.GetString("PrintTableColumnCellTemplateNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string PrintTableColumnHeaderNode {
            get {
                return ResourceManager.GetString("PrintTableColumnHeaderNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string PrintTableColumnNode {
            get {
                return ResourceManager.GetString("PrintTableColumnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string PrintTableColumnsNode {
            get {
                return ResourceManager.GetString("PrintTableColumnsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string PrintTableNode {
            get {
                return ResourceManager.GetString("PrintTableNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cells.
        /// </summary>
        public static string PrintTableRowCellsNode {
            get {
                return ResourceManager.GetString("PrintTableRowCellsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string PrintTableRowNode {
            get {
                return ResourceManager.GetString("PrintTableRowNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string PrintTableRowsNode {
            get {
                return ResourceManager.GetString("PrintTableRowsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string PrintUnderlineNode {
            get {
                return ResourceManager.GetString("PrintUnderlineNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintView.
        /// </summary>
        public static string PrintView {
            get {
                return ResourceManager.GetString("PrintView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfinniPlatform PrintView Designer.
        /// </summary>
        public static string PrintViewDesignerName {
            get {
                return ResourceManager.GetString("PrintViewDesignerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Data.
        /// </summary>
        public static string PrintViewPreviewDataDialog {
            get {
                return ResourceManager.GetString("PrintViewPreviewDataDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string PrintViewStyle {
            get {
                return ResourceManager.GetString("PrintViewStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string PrintViewStylePropertiesDockPanel {
            get {
                return ResourceManager.GetString("PrintViewStylePropertiesDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string PrintViewStylesDockPanel {
            get {
                return ResourceManager.GetString("PrintViewStylesDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        public static string PrintViewTreeDockPanel {
            get {
                return ResourceManager.GetString("PrintViewTreeDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer.
        /// </summary>
        public static string PrintViewViewerDockPanel {
            get {
                return ResourceManager.GetString("PrintViewViewerDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string PropertyEditorBarcodeQrErrorCorrectionHigh {
            get {
                return ResourceManager.GetString("PropertyEditorBarcodeQrErrorCorrectionHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string PropertyEditorBarcodeQrErrorCorrectionLow {
            get {
                return ResourceManager.GetString("PropertyEditorBarcodeQrErrorCorrectionLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string PropertyEditorBarcodeQrErrorCorrectionMedium {
            get {
                return ResourceManager.GetString("PropertyEditorBarcodeQrErrorCorrectionMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartile.
        /// </summary>
        public static string PropertyEditorBarcodeQrErrorCorrectionQuartile {
            get {
                return ResourceManager.GetString("PropertyEditorBarcodeQrErrorCorrectionQuartile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Format.
        /// </summary>
        public static string PropertyEditorDisplayFormatDialog {
            get {
                return ResourceManager.GetString("PropertyEditorDisplayFormatDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reformat.
        /// </summary>
        public static string ReformatButton {
            get {
                return ResourceManager.GetString("ReformatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace current PrintView?.
        /// </summary>
        public static string RelpaceCurrentPrintView {
            get {
                return ResourceManager.GetString("RelpaceCurrentPrintView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace content &apos;{0}&apos; on &apos;{1}&apos;?.
        /// </summary>
        public static string ReplaceElementQuestion {
            get {
                return ResourceManager.GetString("ReplaceElementQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate0.
        /// </summary>
        public static string RotationRotate0 {
            get {
                return ResourceManager.GetString("RotationRotate0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate180.
        /// </summary>
        public static string RotationRotate180 {
            get {
                return ResourceManager.GetString("RotationRotate180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate270.
        /// </summary>
        public static string RotationRotate270 {
            get {
                return ResourceManager.GetString("RotationRotate270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate90.
        /// </summary>
        public static string RotationRotate90 {
            get {
                return ResourceManager.GetString("RotationRotate90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceFormat.
        /// </summary>
        public static string RunSourceFormatProperty {
            get {
                return ResourceManager.GetString("RunSourceFormatProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowHeader.
        /// </summary>
        public static string ShowHeaderProperty {
            get {
                return ResourceManager.GetString("ShowHeaderProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowText.
        /// </summary>
        public static string ShowTextProperty {
            get {
                return ResourceManager.GetString("ShowTextProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string SizeHeightProperty {
            get {
                return ResourceManager.GetString("SizeHeightProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SizeUnit.
        /// </summary>
        public static string SizeSizeUnitProperty {
            get {
                return ResourceManager.GetString("SizeSizeUnitProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cm.
        /// </summary>
        public static string SizeUnitCm {
            get {
                return ResourceManager.GetString("SizeUnitCm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string SizeUnitIn {
            get {
                return ResourceManager.GetString("SizeUnitIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mm.
        /// </summary>
        public static string SizeUnitMm {
            get {
                return ResourceManager.GetString("SizeUnitMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pt.
        /// </summary>
        public static string SizeUnitPt {
            get {
                return ResourceManager.GetString("SizeUnitPt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Px.
        /// </summary>
        public static string SizeUnitPx {
            get {
                return ResourceManager.GetString("SizeUnitPx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string SizeWidthProperty {
            get {
                return ResourceManager.GetString("SizeWidthProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        public static string SourceExpression {
            get {
                return ResourceManager.GetString("SourceExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source JSON has wrong format: &apos;{0}&apos;..
        /// </summary>
        public static string SourceJsonHasWrongFormat {
            get {
                return ResourceManager.GetString("SourceJsonHasWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string SourceProperty {
            get {
                return ResourceManager.GetString("SourceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string StyleProperty {
            get {
                return ResourceManager.GetString("StyleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string StylesEditorDialog {
            get {
                return ResourceManager.GetString("StylesEditorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        public static string StylesProperty {
            get {
                return ResourceManager.GetString("StylesProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string TableCategory {
            get {
                return ResourceManager.GetString("TableCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnSpan.
        /// </summary>
        public static string TableCellColumnSpanProperty {
            get {
                return ResourceManager.GetString("TableCellColumnSpanProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowSpan.
        /// </summary>
        public static string TableCellRowSpanProperty {
            get {
                return ResourceManager.GetString("TableCellRowSpanProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string TableColumnHeader {
            get {
                return ResourceManager.GetString("TableColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string TableColumns {
            get {
                return ResourceManager.GetString("TableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string TableRows {
            get {
                return ResourceManager.GetString("TableRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string TextAlignmentCenter {
            get {
                return ResourceManager.GetString("TextAlignmentCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        public static string TextAlignmentJustify {
            get {
                return ResourceManager.GetString("TextAlignmentJustify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string TextAlignmentLeft {
            get {
                return ResourceManager.GetString("TextAlignmentLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string TextAlignmentProperty {
            get {
                return ResourceManager.GetString("TextAlignmentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string TextAlignmentRight {
            get {
                return ResourceManager.GetString("TextAlignmentRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase.
        /// </summary>
        public static string TextCaseLowercase {
            get {
                return ResourceManager.GetString("TextCaseLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string TextCaseNormal {
            get {
                return ResourceManager.GetString("TextCaseNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        public static string TextCaseProperty {
            get {
                return ResourceManager.GetString("TextCaseProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SentenceCase.
        /// </summary>
        public static string TextCaseSentenceCase {
            get {
                return ResourceManager.GetString("TextCaseSentenceCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToggleCase.
        /// </summary>
        public static string TextCaseToggleCase {
            get {
                return ResourceManager.GetString("TextCaseToggleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase.
        /// </summary>
        public static string TextCaseUppercase {
            get {
                return ResourceManager.GetString("TextCaseUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextCategory {
            get {
                return ResourceManager.GetString("TextCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string TextDecorationNormal {
            get {
                return ResourceManager.GetString("TextDecorationNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overline.
        /// </summary>
        public static string TextDecorationOverline {
            get {
                return ResourceManager.GetString("TextDecorationOverline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration.
        /// </summary>
        public static string TextDecorationProperty {
            get {
                return ResourceManager.GetString("TextDecorationProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        public static string TextDecorationStrikethrough {
            get {
                return ResourceManager.GetString("TextDecorationStrikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string TextDecorationUnderline {
            get {
                return ResourceManager.GetString("TextDecorationUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string TextProperty {
            get {
                return ResourceManager.GetString("TextProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string ThicknessAllProperty {
            get {
                return ResourceManager.GetString("ThicknessAllProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string ThicknessBottomProperty {
            get {
                return ResourceManager.GetString("ThicknessBottomProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        public static string ThicknessLeftProperty {
            get {
                return ResourceManager.GetString("ThicknessLeftProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        public static string ThicknessRightProperty {
            get {
                return ResourceManager.GetString("ThicknessRightProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SizeUnit.
        /// </summary>
        public static string ThicknessSizeUnitProperty {
            get {
                return ResourceManager.GetString("ThicknessSizeUnitProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string ThicknessTopProperty {
            get {
                return ResourceManager.GetString("ThicknessTopProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListView.
        /// </summary>
        public static string ViewTypeListView {
            get {
                return ResourceManager.GetString("ViewTypeListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectView.
        /// </summary>
        public static string ViewTypeObjectView {
            get {
                return ResourceManager.GetString("ViewTypeObjectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewType.
        /// </summary>
        public static string ViewTypeProperty {
            get {
                return ResourceManager.GetString("ViewTypeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string VisibilityAlways {
            get {
                return ResourceManager.GetString("VisibilityAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string VisibilityNever {
            get {
                return ResourceManager.GetString("VisibilityNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string VisibilityProperty {
            get {
                return ResourceManager.GetString("VisibilityProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string VisibilitySource {
            get {
                return ResourceManager.GetString("VisibilitySource", resourceCulture);
            }
        }
    }
}
